sudo: required
language: node_js
services:
  - docker
env:
  global:
    - SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
# takes encrypted service-account key from service-account.json.enc, descrypts and adds to service-account.json
  - openssl aes-256-cbc -K $encrypted_9f3b5599b056_key -iv $encrypted_9f3b5599b056_iv -in service-account.json.enc -out service-account.json -d
# Google SDK is needed in order to later run gcloud CLI commands
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
# Travis needs to get access to our service account which needs to be created beforehand in Google cloud side
# Service account needs to be attached in used service i.e. kubernates engine in this case. At same time
# service account key is created
  - gcloud auth activate-service-account --key-file service-account.json
  - gcloud config set project multi-k8s-363707
  - gcloud config set compute/zone europe-north1-a
  - gcloud container clusters get-credentials multi-client

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
#Add test cases here
  - docker build -t janimkok/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true janimkok/react-test npm test

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master
